# Generated by Django 2.2.2 on 2019-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190701_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='identifier',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
