# Generated by Django 2.2.3 on 2019-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190702_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/default.png', upload_to='avatars/'),
        ),
    ]
